### ISSUE TITLE
Add assertions

### ISSUE THREAD

**Issue by Gerhut** [Gerhut/axiosist#16]

**Comment by Shyam-Chen** [comment]
Use Jest assertions. https://jestjs.io/docs/en/expect

**Comment by Gerhut** [comment]
> Use Jest assertions. https://jestjs.io/docs/en/expect

Thanks for your suggestions, actually I am not sure if there should are some assertions like superagent have, such as

```js
axiosist(app).get('/').expect(200, 'Response code is not 200')
```

But these years the async / await is more and more used and the response object seems easy to get out of the promise, such as

```js
const response = await axiosist(app).get('/')
response.should.have.property('statusCode', 200, 'Response code is not 200')
```

I will add async / await usages to README and recommended this usage.
