### ISSUE TITLE
axiosist not cleaning up after itself

### ISSUE THREAD

**Issue by johncmunson** [Gerhut/axiosist#27]
Step 1:
```
const axiosist = require('axiosist')
const { app } = require('../../index')
const { Todo } = require('../../models')

describe('GET /todos', () => {
  it('returns a list of todos', async () => {
    const { data: todos } = await axiosist(app).get('/todos')
    todos.forEach(todo => {
      expect(Todo.validate(todo)).toEqual(true)
    })
  })
})
```
Step 2:
```
$ jest
```
Step 3:
```
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests.
```

Note: It appears supertest has this exact same [issue](https://github.com/visionmedia/supertest/issues/520#issuecomment-557528742)

**Comment by Gerhut** [comment]
Hi @johncmunson 

Unfortunately I can not reproduce your issue. Is your `app` a server and already set to listening in your `../../index` module? If so, you have to manually close it, which is by design

**Comment by Gerhut** [comment]
I have gone through https://github.com/facebook/jest/issues/9227 and found that you may have other open sockets that keeps jest from automatic exit. Is it also the root cause of this issue?

**Comment by johncmunson** [comment]
@Gerhut I've resolved the issue. My app was not already listening on a socket when it was being passed to axiosist... the real issue was that the knex.js connection pool needed to be manually destroyed after Jest tests finished running, which I was failing to do. Sorry for the hassle
