### ISSUE TITLE
Should throw for non-2XX responses

### ISSUE THREAD

**Issue by kenberkeley** [Gerhut/axiosist#45]
According to [Axios's doc](https://axios-http.com/docs/handling_errors), any non-2xx response will be thrown.

But in `axiosist` is not the case. Why?

**Comment by kenberkeley** [comment]
Oh, I see

https://github.com/Gerhut/axiosist/blob/0fcc68aead45f5080b4811088e60f15b3653a8ed/index.js#L98

Use `axios.create({ adapter: axiosist.createAdapter(app) })` instead.

**Comment by Gerhut** [comment]
In my daily unit test practice, both the 2xx and non-2xx responses should be tested equally, but `try ... catch` structure is usually harder to put in the assertion, nor has less type inferences.

I have to write something like (TypeScript):

```ts
try {
  await axiosist(app).get('/400')
  assert.fail('should throw an error')
} catch (e) {
  // e is of unknown type
  assert.equal(e.response.status, 400)
}

// or in newer Node.js

await assert.rejects(axiosist(app).get('/400'), (e: AxiosError) => { // need to specify AxiosError here
  assert.equal(e.response.status, 400)
})
```

I prefer

```ts
const response = await axiosist(app).get('/400') // auto inferred AxiosResponse type
assert(response.status, 400)
```

Even you are writing positive (2xx) tests, it's a good practice that does validate status here before looking into the response body.
